### ISSUE TITLE
Using the ULP with CHMT48VB

### ISSUE THREAD

**Issue by Chaosmann** [sparkfunX/Desktop-PickAndPlace-CHMT36VA#11]
What do I have to change to get this work with the bigger maschine with more feeders? I’ve found the line with “int MAX_FEEDER = 30” and changed it to 64 but it still don’t insert the feeders with an ID over 30 out of my local document. Until ID 30 everything works.

**Comment by berniwa** [comment]
Hey, could you check if my latest version of the ULP fixes that for you?
https://github.com/berniwa/Desktop-PickAndPlace-CHMT36VA

**Comment by Chaosmann** [comment]
It works now, somehow my Eagle didn't reloaded the file properly.

**Comment by nseidle** [comment]
Closing out.
