### ISSUE TITLE
Placement data not coming through for bottom parts

### ISSUE THREAD

**Issue by nseidle** [sparkfunX/Desktop-PickAndPlace-CHMT36VA#13]
I think it has to do with the outline auto-detection but bottom parts are not lining up as expected.

The solution for now (because paste is sitting) is to flip the board in eagle, and output top placement data per usual methods.

**Comment by nseidle** [comment]
I should be specific: the placement data is coming through it's just wrong and it's just the X coordinate.

**Comment by berniwa** [comment]
Could you send your file?
Do you have a proper dimension layer outline?
Have you tried to specify the board width/height manually?

**Comment by THX2112** [comment]
How wrong? Our X placement is off by a fraction of a mm, but it's close enough that the paste pulls the part in during reflow. I had assumed this was due to sloppy PCB alignment on our part.

Checking "Flip Horizontal" works for us (except for the slight misalignment). All of our PCBs have components on the bottom and we had to flip the PCBs in Eagle before using the ULP came along.

**Comment by nseidle** [comment]
Here is a pic of the BRD: 

![image](https://user-images.githubusercontent.com/117102/38164585-09ae62ee-34c4-11e8-8eef-2c68e73f48e9.png)

Here is the BRD: [magarray-halleffect-Panel.zip](https://github.com/sparkfunX/Desktop-PickAndPlace-CHMT36VA/files/1865605/magarray-halleffect-Panel.zip)

I believe the issue is that that our v-score dimension lines are causing the "Automatic offset" feature to incorrectly believe the width of the board is wider and taller than it actually is. I am away from our machine so I can't verify. The automatic offset feature is really nice, it's our panel files that are the problem.

I think the solution is to change our [panelization ULP](https://github.com/sparkfun/SparkFun_Eagle_Settings/blob/master/ulp/SparkFun-Panelizer.ulp) to draw the v-score lines on a different layer (not dimension, maybe mill layer) and then change our [CAM ulp](https://github.com/sparkfun/SparkFun_Eagle_Settings/blob/master/ulp/SparkFun-CAMmer.ulp) to then pick up the mill layer and export it to the GKO gerber.

I'm going to close out this issue. Let me know if anyone else has similar issues.
