### ISSUE TITLE
Running ulp with a negative angle results in file format error

### ISSUE THREAD

**Issue by LGKev** [sparkfunX/Desktop-PickAndPlace-CHMT36VA#14]
![image](https://user-images.githubusercontent.com/14641166/37996293-61b019b2-31d4-11e8-93cc-aaf4ce008431.png)

**Comment by berniwa** [comment]
Did you add a negative offset in the google docs feeder file?
Eagle should normally only produce positive rotations.

**Comment by nseidle** [comment]
Ya, the component had a negative offset in the google doc.

I added a check in the ULP in [the latest commit](https://github.com/sparkfunX/Desktop-PickAndPlace-CHMT36VA/commit/d292774dc50a0786f97765fc3274936e115d9dc9). Should be protected now.
