### ISSUE TITLE
No "Parts not assigned", unassigned parts sent to feeder #25

### ISSUE THREAD

**Issue by THX2112** [sparkfunX/Desktop-PickAndPlace-CHMT36VA#16]
See here:

![](https://i.imgur.com/Ps0fx22.png)

![](https://i.imgur.com/KSC6Ezy.png)

![](https://i.imgur.com/qp83Dna.png)

Commenting line 249 "fixes" it.

```c
	//Check if name from spreadsheet is inside name of component
	int pos = strstr(strlwr(name), strlwr(stringTrim(fname)));
	if(pos != -1){ //Found!
	//	return i;
	}
```

![](https://i.imgur.com/oVe9CLA.png)

![](https://i.imgur.com/f1sBfaL.png)

![](https://i.imgur.com/AUpCsbs.png)

**Comment by nseidle** [comment]
Hmm, commenting out line 249 will have lots of bad side effects.

It looks like a blank feeder, in your case feeder 25, will be incorrectly associated with the new/unknown part (3904 in your case). Let me have a look...

**Comment by nseidle** [comment]
I'm able to replicate, and fix:

Bad:
![image](https://user-images.githubusercontent.com/117102/38166113-954ba0ca-34db-11e8-9b83-7333c16ba574.png)

![image](https://user-images.githubusercontent.com/117102/38166116-a51dab60-34db-11e8-8bfd-12612ebce2a8.png)

And with the fix in place:

![image](https://user-images.githubusercontent.com/117102/38166127-ccd23eaa-34db-11e8-8670-af87da5a2325.png)

![image](https://user-images.githubusercontent.com/117102/38166130-d70e4bac-34db-11e8-89f2-c9744fc7f27b.png)

Please pull the latest version and let us know if it helps.

**Comment by THX2112** [comment]
Yes, worked. Thanks.

**Comment by berniwa** [comment]
I'm out of office on the 06.04.18.
