### ISSUE TITLE
Suggested folder/format for random notes

### ISSUE THREAD

**Issue by colinoflynn** [sparkfunX/Desktop-PickAndPlace-CHMT36VA#17]
I'd like to see about moving some of  my "random notes" into this repo to reduce cyber-clutter. You can see my repo at https://github.com/colinoflynn/chmt36va_hints .

Any preferred method here? I'm thinking a new folder that has a bunch of markdown files (or maybe just one big one), can be sorted into folders as well for further clarification.

That way other people can make small notes & push them in. Basically like a "tips-n-tricks" section - either done as one large markdown (might be easiest to browse) or a bunch of small snippets.

Wanted to get some input before doing a PR. Feel free to create such structure and I can PR into the right locations.

**Comment by nseidle** [comment]
I think a tips and tricks folder with a bunch of images and a markdown file is a fine solution.

https://github.com/sparkfunX/Desktop-PickAndPlace-CHMT36VA/tree/master/Tips-And-Tricks

So added.
