### ISSUE TITLE
Down-looking Vision not recognizing fiducials 

### ISSUE THREAD

**Issue by andrewcilia** [sparkfunX/Desktop-PickAndPlace-CHMT36VA#22]
The down looking camera "Find Target" button is not working for automated recognition of fiducial marks.
Going into the hidden menu and performing a Vision Set calibration on the down-looking camera while looking at a 1mm round fid seems to work once you setup the threshold to about 85 and the Rsize to 30,30.  you must be in Binary image to see it.  
The problems I can see are:
1- these new values are not saved 
2- the PCB calibration "Find Target" still does not work after performing this calibration

![IMG_8853](https://user-images.githubusercontent.com/24208586/54360393-c80b3e80-4632-11e9-9aae-da6d2d8a234f.jpg)

**Comment by nseidle** [comment]
Thanks for reporting! As mentioned on the mailing list, we don't control the software so we can't fix this. I hope OpenPNP can be an option in the near future.

Closing the issue for now.
