### ISSUE TITLE
Work File Error - DPV File Error

### ISSUE THREAD

**Issue by dallaslayman** [sparkfunX/Desktop-PickAndPlace-CHMT36VA#26]
I am operating a CHM-T48VB and it was working fairly well a few weeks ago but however, it seems to be having trouble reading the .dpv file. I am running the "ConvertToCharm" ULP in EAGLE and saving the .dpv file, but when I save to flash, import on the PnP machine and go to run, the file shows no components at all and when I select "load", I receive the "work file error" message. 

I was running the machine a few weeks ago with minor issues but none related to the work file not reading. When I run the "example board to convert" brd file, it will show its components and load without error.. So I am unsure what the difference between the brd files are which the ULP is not converting properly. Any ideas or suggestions?

Thanks

**Comment by berniwa** [comment]
How many different parts do you want to mount per board?
I had an issue once, where the file wouldn't load correctly with <3 parts in the BOM.
Could you attach your file?

**Comment by dallaslayman** [comment]
About 10 different parts. Which file are you referring to? The .dpv converted file or the brd file?

**Comment by berniwa** [comment]
The best thing would be the brd file, ich you can share it.

**Comment by dallaslayman** [comment]
Hmm, I cannot share the one I am working on currently, if its possible to talk through the issue that would be best.

Since this sounds like a file-conversion problem, I can send you a sample board and we can troubleshoot with the sample board. I am thinking the issue should be consistent.

**Comment by berniwa** [comment]
I guess, that there is not much secret in the DPV file, could you maybe send that first?
Maybe I see an easy fix right away.

**Comment by dallaslayman** [comment]
Do you have an email I can send it to?

**Comment by dallaslayman** [comment]
This is a folder with a few different subfolders separating .brd files that DO load on the machine after I convert and .brd that DO NOT load on the machine when I convert. It seems like any in-house .brd files I convert, are not converting correctly and cannot load on the PnP machine, I receive a "Work File Error" message when I select load. The files in the "Loads" folder are sample .brd files I found online that convert and load with no issue. If you see any difference or can think of why these files aren't converting and loading properly, please let me know! I am out of ideas! 

Thanks

[PnP Troubleshoot.zip](https://github.com/sparkfunX/Desktop-PickAndPlace-CHMT36VA/files/3143332/PnP.Troubleshoot.zip)

**Comment by nseidle** [comment]
Hi - It's the decimal point in your file name. Change it to Fuse
Board_V10-top.dpv. Works fine.
-- 
Nathan Seidle, Founder

**Comment by dallaslayman** [comment]
Wow, you are awesome. Thanks

**Comment by owendelong** [comment]
Shouldn't this issue be closed?

**Comment by nseidle** [comment]
Thanks!
